### ISSUE TITLE
.NET SDK Documentation, .EventFlushInterval() config needs to be updated 

### ISSUE THREAD

**Issue by NickMSW** [launchdarkly/LaunchDarkly-Docs#140]
When reading through the documentation for customizing our LD client, I set the event flush interval according to the documentation:
https://docs.launchdarkly.com/sdk/server-side/dotnet#customizing-your-client
 
`Configuration config = LaunchDarkly.Client.Configuration.Builder("YOUR_SDK_KEY")
    .EventFlushInterval(TimeSpan.FromSeconds(2)).Build();
LdClient ldClient = new LdClient(config);` 

However, in code, that method is deprecated.
![image](https://user-images.githubusercontent.com/55797929/110841703-d9ac6e80-826b-11eb-8045-5ab8acd105a2.png)

Using LaunchDarkly.ServerSdk Version=5.14.1.0

**Comment by bwoskow-ld** [comment]
This issue is a bit stale; the issue in question now references [this page/section](https://docs.launchdarkly.com/sdk/features/config#net), but regardless, this is resolved in a currently-open pull request on our private docs repository mirror, and we plan on merging and deploying the PR this week.

**Comment by bwoskow-ld** [comment]
This content was updated as part of this week's .NET SDK 6.0.0 release.
