### ISSUE TITLE
Uses restricted Non SDK interfaces

### ISSUE THREAD

**Issue by SirMrMa** [launchdarkly/LaunchDarkly-Docs#167]
https://developer.android.com/about/versions/11/non-sdk-11
Conscrypt setHostname() and setUseSessionTickets().

**Comment by bwoskow-ld** [comment]
Hi @SirMrMa ,

This repository is intended to allow for third-party contributions to LaunchDarkly's documentation. If you're looking for a particular documentation change, please provide additional details such as the page you want updated and what content is incorrect / incomplete.

If you are instead looking for a change in a different resource, such as in our [Android SDK](https://github.com/launchdarkly/android-client-sdk), please file a request in the appropriate repository -- and also with sufficient details.

Cheers,
@bwoskow-ld

**Comment by SirMrMa** [comment]
Sorry my mistake, I was following the flutter sdk git link which I see now directed me to the documentation repo.
