### ISSUE TITLE
Is the NextJS Documentation Incorrect?

### ISSUE THREAD

**Issue by TwisterMc** [launchdarkly/LaunchDarkly-Docs#237]
https://docs.launchdarkly.com/guides/platform-specific/nextjs#client-side-rendering

This help article talks about using the `LAUNCHDARKLY_SDK_CLIENT` but shouldn't it be `LAUNCHDARKLY_CLIENT_SIDE_ID`?

When I was going through the setup, I got errors saying my client side ID was invalid, but the documentation says over and over to use `LAUNCHDARKLY_SDK_CLIENT`

Additionally, if it is supposed to be the `LAUNCHDARKLY_SDK_CLIENT` then why are we asking it to `clientSideID`?

```
export default withLDProvider({
  clientSideID: process.env.LAUNCHDARKLY_SDK_CLIENT,
})(MyApp);
```

**Comment by scribblingfox** [comment]
Hey @TwisterMc thanks for this question! Roping in our SDK team manager to look into this.

**Comment by bwoskow-ld** [comment]
Hi @TwisterMc,

Yes, you're right -- the `LAUNCHDARKLY_SDK_CLIENT` environment variable refers to the LaunchDarkly client-side ID as opposed to an SDK client instance. We can update the documentation to name this environment variable `LAUNCHDARKLY_CLIENT_SIDE_ID` to clarify it for future readers.

If the `LAUNCHDARKLY_SDK_CLIENT` environment variable resolves to your LaunchDarkly client-side ID, then the error message is accurate -- in this case, you're passing in a value that LaunchDarkly does not recognize as a valid client-side ID. Double check that the environment variable contains a valid client-side ID value.

If you need further assistance connecting the SDK to LaunchDarkly, feel free to reach out to our [support team](https://support.launchdarkly.com).

Cheers,
@bwoskow-ld

**Comment by TwisterMc** [comment]
Thanks everyone. Updating to `LAUNCHDARKLY_CLIENT_SIDE_ID` will help future users.

I've got my first LaunchDarkly flag up and running so it was a success!
