### ISSUE TITLE
Invalid snippet for BigSegment Python

### ISSUE THREAD

**Issue by ktollec-ledger** [launchdarkly/LaunchDarkly-Docs#247]
On https://github.com/launchdarkly/LaunchDarkly-Docs/blob/main/src/content/topics/sdk/features/big-segments.mdx#python
The snippet shows the following line :
```python
client = LaunchDarkly::LDClient.new(sdk_key, config)
```
which results as a syntax error, "::" not being a valid construct in Python

**Comment by mmrj** [comment]
Thank you for bringing this to our attention, @ktollec-ledger ! 

We've updated the sample here based on your feedback. You can read the corrected version at https://docs.launchdarkly.com/sdk/features/big-segments#python.
