### ISSUE TITLE
Save with comment button is greyed out to create a custom property under settings even with admin access. Does login user need specific access rights?

### ISSUE THREAD

**Issue by rselvamdeg** [launchdarkly/LaunchDarkly-Docs#252]

**Comment by mmrj** [comment]
Hi @rselvamdeg , 

Thanks for reaching out. On the **Feature flags > Settings** page, in the "Custom properties" section, click "+ Add custom property" and then choose a property type from the menu. Once you've selected a property type, the "Save changes" button becomes enabled. For more information, you can read the [Custom properties](https://docs.launchdarkly.com/home/connecting/custom-properties) documentation. 

If you still have questions, you can reach our Support team at https://support.launchdarkly.com/hc/en-us. 

Thanks!
LaunchDarkly Docs Team
