### ISSUE TITLE
Different subset of user for two flags with same percentage rollout?

### ISSUE THREAD

**Issue by gerrytan** [launchdarkly/LaunchDarkly-Docs#265]
Is it correct to assume two different flags set with same default rule of 25% percentage rollout will target different subset of users?

I can't find this information anywhere in https://docs.launchdarkly.com/sdk/concepts/flag-evaluation-rules#percentage-rollouts (percentage rollout section -- [code ref](https://github.com/launchdarkly/LaunchDarkly-Docs/blob/main/src/content/topics/sdk/concepts/flag-evaluation-rules.mdx)).

**Comment by gerrytan** [comment]
I just figured out the bucketing salt can be adjusted in the settings tab. I assume for 2 flags on different project, they will target consistent subset of percentage rollout user given the same salt and flag key?

**Comment by gerrytan** [comment]
Confirmed: percentage rollout will target same user given following are the same: flag key, bucketing salt and user identifier.

**Comment by scribblingfox** [comment]
Hey @gerrytan, thanks for showing your work on this--we can definitely update the docs to make this clearer and prevent the confusion for future readers. Thanks for the contribution! :)
