### ISSUE TITLE
Evaluation reasons docs - pros/cons

### ISSUE THREAD

**Issue by captain-jamesma** [launchdarkly/LaunchDarkly-Docs#273]
I would really benefit from using the additional information provided from enabling https://github.com/launchdarkly/LaunchDarkly-Docs/blob/main/src/content/topics/sdk/concepts/evaluation-reasons.mdx, but it's not clear from the docs if there are meaningful performance penalties for enabling the feature. 

My tests seem to suggest the difference is negligible, but I'd like some explicit clarity around the performance implications if possible.

**Comment by scribblingfox** [comment]
Hi @captain-jamesma ! Thanks for your feedback. I'll add your request to our issue tracker and we'll get it prioritized for an upcoming iteration. Unfortunately the tracker is internal to LaunchDarkly employees, so you won't be able to follow along in real time, but rest assured: we got your request, it matters to us, and we'll investigate if it's possible to accurately document the performance implications of enabling eval reasons, given how unique each configuration is. Thanks again!
