### ISSUE TITLE
How to set up jest-launchdarkly-mock with create-react-app 5?

### ISSUE THREAD

**Issue by deammer** [launchdarkly/LaunchDarkly-Docs#291]
Hi, I am trying to use `jest-launchdarkly-mock` with `create-react-app@5`. [The LD documentation](https://docs.launchdarkly.com/guides/infrastructure/unit-tests#overview) says that I should add the following line to my Jest configuration:

```js
// jest.config.js
module.exports = {
  setupFiles: ['jest-launchdarkly-mock'],
}
```

However, CRA 5 doesn't ingest the `jest.config.js` file because it generates its own configuration.

The `setupFiles` property is also not allowed in the `package.json` file:

```js
// package.json
{
  "jest": {
    "setupFiles": ["jest-launchdarkly-mock"]
  }
}
```

This throws the following error:
> These options in your package.json Jest configuration are not currently supported by Create React App:
>
>  • setupFiles

How would you recommend using `jest-launchdarkly-mock` with CRA?

**Comment by yusinto** [comment]
@deammer this is not an issue specific to jest-launchdarkly-mock. However according to the [create react app docs](https://create-react-app.dev/docs/running-tests/#initializing-test-environment), you can add the following import to the existing `src/setupTests.js` and any code in that file will be automatically executed before running tests. This should solve the issue.

```tsx
// include this in the existing cra src/setupTests.js
import 'jest-launchdarkly-mock'
```
