### ISSUE TITLE
[question] change multiple feature flags at the same time

### ISSUE THREAD

**Issue by silvioprog** [launchdarkly/LaunchDarkly-Docs#295]
Hi LD team.

Is there any feature allowing the user to change multiple feature flags at the same time for one or more users?

For example, imagine these FFs below (with `true/false` variations):

```
FEATURE_FLAG_A
FEATURE_FLAG_B
```

and these users:

```
a@a.a
b@b.b
```

is there any way to apply this at the same time instead of one by one?

```
a@a.a:
FEATURE_FLAG_A = true
FEATURE_FLAG_B = false

b@b.b
FEATURE_FLAG_A = true
FEATURE_FLAG_B = true
```

Not sure if here is the correct place to ask, but I found this link googling by `launchdarkly+change+multiple+flags`

TIA for any help!

**Comment by scribblingfox** [comment]
Hi @silvioprog ! You'd have better luck searching our documentation directly: docs.launchdarkly.com. Alternatively, you can open a support ticket. There's also a link to that on our docs site. I'm going to close this, but if you have any questions or feedback on the docs, feel free to get in touch again!
