### ISSUE TITLE
Custom Attributes - Documentation lacks clarity around persistence

### ISSUE THREAD

**Issue by ckartik** [launchdarkly/LaunchDarkly-Docs#329]
There is a lack of clarity around attribute persistence in Launch Darkly servers for 5.x SDK and the broader LD API.

In particular if we use the [Identify endpoint](https://docs.launchdarkly.com/sdk/features/identify) as follows:
```go
user := userBuilder.Custom("Attribute-1", "value").Build
client.Identify(user)
```

There's no clear expectation of the attribute being persisted in the LD API as per the documents. The ask is to update the Documentation to provide one of the following clarifications around support for persisted custom attributes:
- Unimplemented (no persistence)
- Unsupported (no guarantee of persistence or time of persistence)
- Fully Supported

**Comment by mmrj** [comment]
Hi @ckartik , thanks for reaching out. Which SDK (language and version) are you using?

**Comment by mmrj** [comment]
The LaunchDarkly SDKs are specialized for the tasks of evaluating feature flags in your application and generating analytics events based on those evaluations.

When your application starts up, your code should initialize the LaunchDarkly SDK you're working with. When a customer encounters a feature flag in your application, your code should use the SDK to [evaluate the feature flag](https://docs.launchdarkly.com/sdk/features/evaluating) and retrieve the appropriate flag variation for that customer. 

The LaunchDarkly UI displays the user objects that your application has [identified](https://docs.launchdarkly.com/sdk/features/identify) or [evaluated flags for](https://docs.launchdarkly.com/sdk/features/evaluating), on the [Users list](https://docs.launchdarkly.com/home/users/users-list), including any attributes that you have added to the object. As described in that topic, under [User storage](https://docs.launchdarkly.com/home/users/users-list#user-storage), users appear on the list for 30 days.

The LaunchDarkly API is separate from the LaunchDarkly SDKs. It allows you to perform all of the functions available in the LaunchDarkly UI through a REST API. To learn more, you can read [Comparing LaunchDarkly’s SDKs and REST API](https://docs.launchdarkly.com/guide/api/comparing-sdk-rest-api).
