### ISSUE TITLE
How to cancel a plan

### ISSUE THREAD

**Issue by reymon359** [launchdarkly/LaunchDarkly-Docs#338]
I can't find any documentation about cancelling a plan.

I want to stop using LaunchDarkly and can't cancel my plan

**Comment by mmrj** [comment]
Hello! To cancel your subscription, [contact Support](https://support.launchdarkly.com/hc/en-us/).

**Comment by reymon359** [comment]
> Hello! To cancel your subscription, [contact Support](https://support.launchdarkly.com/hc/en-us/).

Thanks @mmrj , will contact them 😊

I still think you guys should add that to the account settings or docs to help future users. Any plan on doing so?

**Comment by mmrj** [comment]
@reymon359 Yes, we're discussing internally on the most helpful spot, you should see the update soon. Thanks for suggesting.

**Comment by tobthecreator** [comment]
we're deactivating our account because LD features don't match with our current product needs, but not being able to deactivate on my own is such a scummy tactic that i'm reevaluating if I'll ever use this service again

**Comment by scribblingfox** [comment]
@tobthecreator Hi Tyler! I'm LaunchDarkly's documentation manager. Thank you for your feedback on our product. We'll get these docs updated next week. There's definitely a documentation gap to address here.

I understand your frustration with having to take an extra step to cancel your plan. Ultimately, the docs team doesn't make product decisions about what features we build, but I've raised this topic with our PMs, so it's definitely on our radar now! Sorry for the rough experience. This kind of feedback really does help us make the product better, so I appreciate you taking the time to leave it.
