### ISSUE TITLE
Incorrect Docs

### ISSUE THREAD

**Issue by KaneTesta** [launchdarkly/LaunchDarkly-Docs#345]
Hey,

Seems like the SDK name in the import is wrong here under React-Web

https://github.com/launchdarkly/LaunchDarkly-Docs/blob/b144251291ee8cf9121a984594b8def174a28847/src/content/topics/sdk/features/logging.mdx

It should be `import { basicLogger } from "launchdarkly-js-client-sdk"` and not `import { basicLogger } from 'launchdarkly-js-sdk-client';`

**Comment by mmrj** [comment]
You are correct! Thanks for pointing this out. We'll get this updated shortly.
