### ISSUE TITLE
Issues with slack integration

### ISSUE THREAD

**Issue by ujwaldhakal** [launchdarkly/LaunchDarkly-Docs#354]
I wanted to do following things with launch darkly (i dont know if its possible or not).
* Add , remove & update custom attributes

Two things:

* Whenever I type `/launchdarkly help` I see the same dialog again but not the list of available commands.  ![image](https://user-images.githubusercontent.com/11195862/236159145-7d8076ea-2802-4aa1-8d4b-072c534e12a8.png)

* And some of the commands like flag, filters doesn't work 
![image](https://user-images.githubusercontent.com/11195862/236162172-432a1def-5156-4a5d-b3b1-634016e305bf.png)

**Comment by scribblingfox** [comment]
@ujwaldhakal Hi Ujwal! We've directed our integrations engineers to this issue and hope to have an update for you soon! Thanks for taking the time to call our attention to this problem.

**Comment by lucywyman** [comment]
Hi @ujwaldhakal!
> Whenever I type /launchdarkly help I see the same dialog again but not the list of available commands.
Those are the available commands! We recently merged the concepts of `filters` and `flags` into `subscriptions`, so the new command `/launchdarkly list` is what you'll use to list your subscriptions for a channel.

That's what the message `The 'filters' command has been removed. Run /launchdarkly list to see subscriptions for this channel` is trying to tell you - is there a way you think we could have said that more clearly?

**Comment by lucywyman** [comment]
Unfortunately adding, removing, and updating custom attributes isn't available through the Slack integration - most of our functionality is around notifications for flag changes, unfurling flag links in Slack, and approving or denying approval requests. The exception to this is being able to toggle flags on or off, but it's functionality we've de-emphasized as users were concerned about toggling being too low friction for a risky action.

**Comment by ujwaldhakal** [comment]
Thank you @lucywyman  that is clear now. May be if you remove them from slack suggestion it might not create confusion
![image](https://user-images.githubusercontent.com/11195862/236454540-f90b0537-6068-450c-84e4-ac881d876450.png)

**Comment by ujwaldhakal** [comment]
Feel free to close this

**Comment by lucywyman** [comment]
Ah, I can definitely see how that's confusing! I'll get those removed ASAP. Thanks!
