### ISSUE TITLE
Reading flags from a file - Client side

### ISSUE THREAD

**Issue by ahmednkhan24** [launchdarkly/LaunchDarkly-Docs#398]
Hello,

I have an existing SPA written in React that uses the LaunchDarkly React SDK for feature flags.
I am writing automation tests for the project using Microsoft's Playwright library.

I am looking for a way to enable/disable feature flags in my tests.
I stumbled upon this [documentation](https://docs.launchdarkly.com/sdk/features/flags-from-files?_gl=1*31dusf*_gcl_au*Nzc0MDMxMjQuMTY5ODA3MTY0Mg..) that recommends reading from a local file, but only provides examples for server side code.

I am looking for any documentation/help on how to read files from a local file in a client side application.
If that is not possible, I am looking for any recommendations on how to toggle Launch Darkly flags in a client side application for automation tests.

Thanks!

**Comment by scribblingfox** [comment]
Hi Ahmed!

Thanks for writing in with this question. We'll look at updating this documentation to be more clear. Can you [open a ticket](https://support.launchdarkly.com/hc/en-us) with our support team to get your question addressed directly? 

Thanks again!
