### ISSUE TITLE
Image links are broken

### ISSUE THREAD

**Issue by anishkny** [launchdarkly/LaunchDarkly-Docs#41]
Clicking on any image e.g. the one subtitled `The dashboard with the "New" button called out.` on [this page](https://docs.launchdarkly.com/home/managing-flags/dashboard) leads to a 404.

![](https://media.giphy.com/media/JqInn6NNBBfHjHOT26/giphy.gif)

**Comment by scribblingfox** [comment]
Hi @anishkny! Thank you so much for calling this to our attention! This is definitely a bug and we're working on fixing it now.

**Comment by scribblingfox** [comment]
Hi again @anishkny! Just wanted to let you know we got this fixed a couple hours after you filed it. I just forgot to close this PR. Sorry about that, and thanks again so much for your input!

**Comment by anishkny** [comment]
Great! Can confirm image links work now. Out of curiosity what was the fix? My guess is it was https://github.com/launchdarkly/LaunchDarkly-Docs/commit/9d9e6aacff5c425d653a37854cc81998547b1577

Also since you folks already have Cypress tests, might be worth adding this as a test case?

Cheers!
