### ISSUE TITLE
best practices: coding page is missing

### ISSUE THREAD

**Issue by tsargent** [launchdarkly/LaunchDarkly-Docs#72]
There's a link to "Coding with feature flags" but the page is missing.

https://github.com/launchdarkly/LaunchDarkly-Docs/blob/d29e5c1e0034983cd83d1f7c5f57cecf0f25a865/src/content/topics/guides/best-practices/index.mdx

https://docs.launchdarkly.com/guides/best-practices/coding

**Comment by scribblingfox** [comment]
@tsargent Thanks so much for calling this to our attention! I accidentally published a link to a doc that hasn't been released yet. 😞 It should be out next week, so watch this space if you're curious.

**Comment by scribblingfox** [comment]
@tsargent I've updated the docs to remove this link. Thank you again!
