### ISSUE TITLE
.Net doc for reading flags from file includes deprecated APIs

### ISSUE THREAD

**Issue by jwooley** [launchdarkly/LaunchDarkly-Docs#74]
The current docs for reading the flags from a file in the server sdk uses the deprecated `WithUpdateProcessorFactory` and `WithEventProcessorFactory` methods. The sample should be updated to:

```
var fileSource = 
    FileComponents.FileDataSource()
        .WithFilePaths("file1.json", "file2.json")
        .WithAutoUpdate(true);
var config =
    Configuration.Builder("sdk api key")
        .UpdateProcessorFactory(fileSource)
        .EventProcessorFactory(Components.NullEventProcessor)
        .Build();
ldClient = new LdClient(config);
```

**Comment by scribblingfox** [comment]
Hi @jwooley ! Thanks so much for filing this issue--I've asked our SDK team to take a look at it. Hope to have an update soon!
