### ISSUE TITLE
Wrong video is showing in create new flag section

### ISSUE THREAD

**Issue by frtali** [launchdarkly/LaunchDarkly-Docs#81]
The wrong video is linked in this section - it is showing the sdk installation video, not creating a flag

https://docs.launchdarkly.com/guides/tutorials/first-flag#creating-a-new-flag

**Comment by scribblingfox** [comment]
@frtali Hi there! Thanks so much for opening this issue. We're investigating!

**Comment by scribblingfox** [comment]
@frtali A fix is building for this issue. Thanks again for your feedback! 👍
