### ISSUE TITLE
Pricing function code doesn't include the updated user object handling code

### ISSUE THREAD

**Issue by frtali** [launchdarkly/LaunchDarkly-Docs#87]
The pricing function example has a section with the complete function code, but the code doesn't include the changes to handling the user object

On page: https://docs.launchdarkly.com/guides/tutorials/rules-and-targeting

Code: @app.route('/')
def pricing():
    """Displays the pricing page."""
    ## Fetch the user's email address. If they aren't logged in,
    ## the stored value will be None.
    email = session.get("email")
    # Since this page doesn't require a logged-in user,
    # tell LD that this is an anonymous user for now.
    # The key is arbitrary and can be anything you want.
    # Here, we wanted to be clear that this was an anonymous
    # user, so we used "anon" as the value.
    user = {
      "key": "anon",
      "anonymous": True
    }
    is_tier_3_enabled = ld_client.variation('pricing-tier-3', user, False)
    return render_template(
      'pricing.html', 
      is_tier_3_enabled=is_tier_3_enabled, 
      email=email,
      key=user['key']
    )

Missing code:

if (email):
  user = user_object_from_email(email)
else:
  ## Since the user isn't logged in,
  ## let's tell LD that this is an anonymous user.
  user = {
    "key": "anon",
    "anonymous": True
  }

**Comment by yozlet** [comment]
Whoops! Thank you for this - am on it.

**Comment by yozlet** [comment]
Okay, _now_ I'm on it. Done.
