### ISSUE TITLE
Request to link LDUser to Users section in node.js server SDK docs

### ISSUE THREAD

**Issue by khasburrahman** [launchdarkly/LaunchDarkly-Docs#94]
In Node.js documentation
https://github.com/launchdarkly/LaunchDarkly-Docs/blob/master/src/content/topics/sdk/server-side/node.mdx

There's a mention about LDUser, in `variation` section
> variation calls take the feature flag key, an LDUser, and a default value.

What is actually LDUser in that context? 
There's no mention of it throughout the node js documents

**Comment by khasburrahman** [comment]
Ah now I see,
It refers to 
https://docs.launchdarkly.com/sdk/server-side/node-js#users

Could we update documentation to hyperlink to Users section? 
LDUser seems like alien word in that documentation

**Comment by eli-darkly** [comment]
Well, it's talking about a specific method call named `variation` which is defined in the SDK. It seems reasonable to assume that any other types it mentions in that context are also things that are defined in the SDK. The reference for all of those things is the generated [API documentation](https://launchdarkly.github.io/node-server-sdk/) which is linked from the first paragraph, where it says "The online API docs contain the programmatic definitions of every type and method." So I'm not against adding a link there, but I do think it's worth keeping in mind that in the context of a software library if you see something that looks like an "alien word" it's very likely to be a symbol that you'll find in the API reference for that library.
